### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by olliemush** [hakluke/wordlesolver#1]
Relitively new to python and can't get it to run without this error (using spyder). I'm just running the code so should I be putting the letters anywhere specific?

Usage: ./wordlesolver.py <letters in word> <letters not in word> <placement>
<letters in word> is just any letters that you know are in the word, without spaces, e.g. vr
<letters not in word> is any letters that you know are NOT in the word, without spaces, e.g. qxu
<placement> should have the actual placement for any letters that went green, with any unknowns marked as an underscore, for example __v_r

NOTE: if you do not have enough information to fill out one of these fields, replace that field with a single question mark "?"
Loaded 15918 words from dictionary.
Traceback (most recent call last):

  File "C:\Users\ollie\Downloads\wordlesolver-main\wordlesolver-main\wordlesolver.py", line 33, in <module>
    if not set(sys.argv[1] + sys.argv[2]) <= allowed:

IndexError: list index out of range

**Comment by hakluke** [comment]
Can you show me what arguments you're running it with?

**Comment by olliemush** [comment]
Sorry wasn't sure how to run it in a command window but all working now, very cool!
